name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-specs:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis

    strategy:
      matrix:
        node-version: [20.3.0]
        redis-version: [7.0.11]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Start Redis v${{ matrix.redis-version }}
        uses: superchargejs/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: install dependencies
        run: pnpm --recursive install
      - name: run specs
        run: pnpm --recursive test
